---
all:
  children:
    csr:
      vars:
        ansible_connection: local
        ansible_user: admin
        ansible_password: admin
        ssh_options: "-o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa -o PubkeyAcceptedKeyTypes=ssh-rsa -o KexAlgorithms=diffie-hellman-group14-sha1"
      hosts:
        csr-pe01:
          ansible_host: 172.20.20.20
          device_name: csr-pe01
          router_id: 192.168.10.11
          loopback_ip: 192.168.10.11
          loopback_mask: 255.255.255.255
          pe_site: red
        csr-pe02:
          ansible_host: 172.20.20.21
          device_name: csr-pe02
          router_id: 192.168.10.12
          loopback_ip: 192.168.10.12
          loopback_mask: 255.255.255.255
          pe_site: purple

    nxos:
      vars:
        ansible_connection: local
        ansible_user: admin
        ansible_password: Cisco1234
        ssh_options: "-o StrictHostKeyChecking=no -o HostKeyAlgorithms=ssh-rsa -o PubkeyAcceptedKeyTypes=ssh-rsa -o KexAlgorithms=diffie-hellman-group14-sha1"
      hosts:
        n9k-ce01:
          ansible_host: 172.20.20.30
          device_name: n9k-ce01
          ce_site: red
        n9k-ce02:
          ansible_host: 172.20.20.31
          device_name: n9k-ce02
          ce_site: purple
